### ISSUE TITLE
Third Party Camera

### ISSUE THREAD

**Issue by kpratapm** [waveform80/picamera#289]
This is not an issue with picamera.
Is it possible to interface a third party camera which does not have an I2C interface but sending video through MIPI CSI interface in YUV422 format. 

Are changes required in kernel driver? Where can I start doing this?

Thank you.

**Comment by 6by9** [comment]
TOTALLY the wrong place to be asking because you're right it has nothing to do with PiCamera.

https://github.com/raspberrypi/linux/issues or https://github.com/raspberrypi/firmware/issues would have been slightly more logical, but it's been covered on the forums. https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=109137 and https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=120702, although both are still alpha or work in progress (I'll get there eventually).
