### ISSUE TITLE
testing new MMAL methods

### ISSUE THREAD

**Issue by 1kane** [waveform80/picamera#373]
I really like the new functionality you descriped here : [Docs](http://picamera.readthedocs.io/en/latest/api_mmalobj.html#file-output-jpeg-capture)
I just testet a bit of your expamles (later i wanna redirect previewPort to stream to a local website) , that should connect like:

-  videoPort->Endoder->outputFile

heres the code (simplified) from your example from the docs
https://gist.github.com/1kane/491b6e9646655daa551915844b9266be#file-mmaltest-py

that should output a file that contains 10sec of camera h.264 encoded data. but the file is empty :(
did i miss something`?

**Comment by waveform80** [comment]
Huh - interesting! Definitely something going wrong here.

**Comment by waveform80** [comment]
Oh, idiot that I am. Was re-factoring the base MMALPythonComponent the other day to have handler methods for all sorts of things that can pass by it and forgot to fix up MMALPythonTarget (unfortunately there's no test suite for Python components in mmalobj yet - and I won't have the time to write one before release, which is part of the reason this API will remain marked "experimental" for 1.13). I'll have this fixed up in a mo.

**Comment by 1kane** [comment]
okay thanks im looking forward to 1.13, when its going to be releaed?
seems to have some very usefull nice features!

**Comment by waveform80** [comment]
Very shortly is my hope - I was hoping to get 1.13 released before xmas last year, but there was far too much going on (house extension, ill health, excuses excuses) so that date slipped. My plan is to clear down as much of the issues list as reasonably possible this week, to make the release is as comprehensive as possible in the vague hope that people won't notice if I disappear for a few months to hunt down some more profitable work :)
