### ISSUE TITLE
picamera.split_recording drops footage in between splits

### ISSUE THREAD

**Issue by nicolashahn** [waveform80/picamera#387]
Sample footage of what I'm talking about, the first one happens about 6 seconds in: https://www.youtube.com/watch?v=BxTM42pAGYw

My code: https://github.com/nicolashahn/pi-helmet-cam/blob/master/camera.py
More specifically the commit used when recording: https://github.com/nicolashahn/pi-helmet-cam/blob/f67d2596d48ae520259fd74d6ca065511d906db9/camera.py

It seems to be dropping about a second or two of footage between splits, but it doesn't happen often, though enough that it happens several times in that clip. Is there any way around this? What's causing it?

I'm using picamera for a motorcycle helmet camera and I wanted a way to just be able to unplug the Pi and have it still keep (almost) all of the footage saved (or in case I get in an accident that destroys or disconnects the camera/Pi but the SD card is intact). So if I'm doing it the wrong way and there's a more correct way to do it I'd like to know about it.

**Comment by paulhothersall** [comment]
line 97 (or 50 on your 2nd link) 

 camera.wait_recording(interval)

loose that, and set your intrarefresh to the desired length of the splits. This is because its ALREADY waiting for a IFrame and other stuff in the split function. Or roll back to a few version earlier, like 2015 version of picamera..... 

If you really want to poke around, its in lines 825-850 range in https://github.com/waveform80/picamera/blob/master/picamera/encoders.py and I swear there is a logical item or edge case issue there, but i have not found it yet. Yes I can repeat your issue, and its much worse when looking at 2 streams.

In the meantime, my suggested "fix" above should handle it for you

**Comment by nicolashahn** [comment]
@paulhothersall your fix worked for me, thank you
