### ISSUE TITLE
Invalid H.264 profile extended

### ISSUE THREAD

**Issue by miguelangelalba** [waveform80/picamera#523]
I'm doing a raspberry streaming project for the university.
In the documentation I saw that I could use the "extended" encoding profile but it is coming out as an invalid argument. Can it be a bug?

`    camera.start_recording(filename, format='h264', quality = 10, level = 4,profile = 'extended')
`

**Comment by 6by9** [comment]
Extended profile encoding is not supported by the firmware.
There is an enum specified in OpenMax and MMAL for them as they are generic APIs, but setting extended profile will fail on the video_encode component.

There is ```OMX_IndexParamVideoProfileLevelQuerySupported``` / ```MMAL_PARAMETER_SUPPORTED_PROFILES``` to query the profiles supported by a component.

NB ```quality``` will mess up bitrate control on h264 encoding. It fixes the min and max quantisation values in the encoder, so is almost a fixed quality method rather than any form of rate control. More normally you'd set the bitrate and allow the codec to control quantisation levels.

**Comment by miguelangelalba** [comment]
Thanks for the support. It took me to confusion the documentation :) 
![imagen](https://user-images.githubusercontent.com/8834745/47749558-a87c0680-dc8d-11e8-9e46-a7a35651ceec.png)

**Comment by waveform80** [comment]
Looks like it's at least a documentation issue; I'll get that fixed for 1.14
